export const footerLinks = [
    {
      id: 1,
      link1: [
        "Get Help",
        "Buy gift cards",
        "Add your restaurant",
        "Sign up to deliver",
        "Create a business account",
        "Promotions",
      ],
    },
    {
      id: 2,
      link2: [
        "Restaurants near me",
        "View all cities",
        "View all countries",
        "Pickup near me",
        "About GoGrocer",
        "English",
      ],
    },
  ];

  export const cities = [
    "Akron",
    "Hartford",
    "Nashville",
    "Providence",
    "Albuquerque",
    "Houston",
    "NewOrleans",
    "Queens",
    "Bridgeport",
    "Indianapolis",
    "Oklahoma City",
    "San Antonio",
    "Concord",
    "McAllen",
    "Omaha",
    "Stony Brook",
    "Dayton",
    "Mesa",
    "Orlando",
    "Tucson",
    "El Paso",
    "Milwaukee",
    "Palm Bay",
    "West Hollywood",
  ];

 export const countries = [
    "Australia",
    "France",
    "Netherlands",
    "Sweden",
    "Belgium",
    "Germany",
    "New Zealand",
    "Switzerland",
    "Canada",
    "Guatemala",
    "Panama",
    "Taiwan (ROC)",
    "Chile",
    "Ireland",
    "Poland",
    "United Kingdom",
    "Costa Rica",
    "Italy",
    "Portugal",
    "United States",
    "Dominican Republic",
    "Japan",
    "South Africa",
    "Ecuador",
    "Kenya",
    "Spain",
    "El Salvador",
    "Mexico",
    "Sri lanka",
  ];